version: '3.1'

services:

  ambiente-mariadb:
    image: mariadb
    container_name: vm_mariadb
    ports:
      - "3306:3306"
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "root"

  ambiente-adminer:
    image: adminer
    container_name: vm_adminer
    restart: always
    ports:
      - 8080:8080

  ambiente-nginx:
    image: nginx:alpine-perl
    container_name: vm_nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./www:/usr/share/nginx/html

  ambiente-mongo:
    image: mongo:jammy
    container_name: vm_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  ambiente-mongo-express:
    image: mongo-express:1.0.2-20
    container_name: vm_mongodb_express
    restart: always
    ports:
      - "8081:8081"
    links:
      - ambiente-mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: vm_mongodb
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
